[tool.poetry]
name = "llm"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
transformers = "*"
jupyterlab = "^4.0.9"
tensorflow = "2.15.0"
torch = "^2.1.1"
keras-nlp = "^0.6.4"
accelerate = "^0.25.0"
flask = "^3.0.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
